name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.builds.os }}

    strategy:
      fail-fast: false

      matrix:
        build_type:
          - Debug
          - Release
        builds:
          - os: ubuntu-latest
            cpp: g++-12
          - os: windows2022
            cpp: cl
    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/out/default/build -DCMAKE_CXX_COMPILER=${{ matrix.builds.cpp }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S ${{ github.workspace }} --preset default

    - name: Build
      run: cmake --build ${{ github.workspace }}/out/default/build --config ${{ matrix.build_type }}

    - name: Test
      run: ctest --test-dir ${{ github.workspace }}/out/default/build --build-config ${{ matrix.build_type }}
