name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.builds.os }}

    strategy:
      fail-fast: false

      matrix:
        build_type:
          - Debug
          - Release
        builds:
          - os: ubuntu-24.04
            preset: ninja-clang16
          - os: ubuntu-24.04
            preset: ninja-clang16
          - os: ubuntu-24.04
            preset: ninja-clang16
          - os: ubuntu-24.04
            preset: ninja-gcc12
          - os: ubuntu-24.04
            preset: ninja-gcc13
          - os: ubuntu-24.04
            preset: ninja-gcc14
          - os: windows-2019
            preset: msvc16-x64
          - os: windows-2019
            preset: msvc16-arm64
          - os: windows-2022
            preset: msvc17-x64
          - os: windows-2022
            preset: msvc17-arm64
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/out/default/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S ${{ github.workspace }} --preset ${{ matrix.builds.preset }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/out/default/build --config ${{ matrix.build_type }}

    - name: Test
      run: ctest --test-dir ${{ github.workspace }}/out/default/build --build-config ${{ matrix.build_type }}
